### ISSUE TITLE
MoreVP Episode 2 - add inflight tx exits

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leap-contracts#86]
# Bounty : MoreVP Episode 2

Implement MoreVP for better UX.

## Scope
- implement an ExitHandler contract the conforms to MoreVP on refactoring branch
- unit tests

## Deliverables
Branch is pushed to GitHub that solves the above.

## Gain for the project
It's good design.

----

https://github.com/omisego/research/blob/master/plasma/plasma-mvp/delegated-exits.md

chose a variant that will work for transactions to smart contracts as well

---

gardener: @johannbarbie  10%
worker: @nanspro 70%
reviewer: 20%

**Comment by troggy** [comment]
Currently UTXOs cannot be exited before a new period is submitted. This is very poor UX, because we are not mining empty blocks now and user may wait quite a while to initiate exit. Also it is very bad security — you should be able to exit your money at any point. 

It could be seen like this: before new period is created all the txs from this period are essentially in flight — from security perspective there is not much difference between tx included in tendermint block only and tx which is not included yet

**Comment by nanspro** [comment]
I tried to implement the paper which is based upon limbo exits and i took help of the matterinc's  `PlasmaContract` implementation but there were some conflicts between the paper and it's implementation so i have a few questions before i can move further.

@johannbarbie could you just check my PR once to see if i am not going in wrong direction and answer some of my queries!!

**Comment by johannbarbie** [comment]
rusty
